--- #YAML:1.0
name:               Geo-Coder-Yahoo
version:            0.43
abstract:           Geocode addresses with the Yahoo! API 
author:
    - Ask Bjoern Hansen <ask@develooper.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Encode:              0
    LWP::UserAgent:      0
    Test::More:          0
    URI:                 1.36
    Yahoo::Search::XML:  20060729.004
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
